name: template

services:
  template:
    build: .
    container_name: template
    restart: always
    ports:
      - "5001:5001"
    
    volumes:
      - template_db_data:/app/data
    
    environment:
      - FLASK_APP=run.py
      - NETWORK_RANGE=192.168.68.0/24
      # - GEMINI_API_KEY=${GEMINI_API_KEY}
    
    dns:
      - 8.8.8.8
      - 8.8.4.4

    x-casaos:
      envs:
        - container: FLASK_APP
          description:
            en_us: Flask application entry point
        - container: NETWORK_RANGE
          description:
            en_us: Network range for ESP32 device discovery (e.g., 192.168.1.0/24)
        - container: GEMINI_API_KEY
          description:
            en_us: Google Gemini API key for AI features (get from https://makersuite.google.com/app/apikey)
      ports:
        - container: "5001"
          description:
            en_us: Web interface port for project management
      volumes:
        - container: /app/data
          description:
            en_us: Application data directory containing SQLite database and files

x-casaos:
  architectures:
    - amd64
    - arm64
  main: template
  author: an0naman
  category: Productivity
  description:
    en_us: "Project management and tracking application with entry management, sensor data monitoring, label printing, and push notifications. Built with Flask and SQLite."
  developer: an0naman
  icon: https://cdn-icons-png.flaticon.com/512/3659/3659898.png
  tagline:
    en_us: "Complete project management solution"
  title:
    en_us: "Project Template Manager"
  index: /
  port_map: "5001"

volumes:
  template_db_data:
    driver: local